### ISSUE TITLE
Support for flexVolumes (Rook/CephFS setup)

### ISSUE THREAD

**Issue by MyleneSimon** [usnistgov/WIPP-backend#36]
**Description**
For dev and testing environments we are using `hostPath` volumes in our single-node Kubernetes clusters. When a workflow is submitted, the workflow yaml file generated by `WIPP-backend` contains definitions of new hostPath volumes for input data (read-only) and output data (read/write). Here for example, workflow with two jobs:
```yaml
volumes:
  - name: "data-volume-input"
    hostPath:
      path: "/data/WIPP-plugins"
  - name: "data-volume-output-5d08443a8870c7246a98b8fe"
    hostPath:
      path: "/data/WIPP-plugins/temp/jobs/5d08443a8870c7246a98b8fe"
  - name: "data-volume-output-5d0844278870c7246a98b8fd"
    hostPath:
      path: "/data/WIPP-plugins/temp/jobs/5d0844278870c7246a98b8fd"
```
Then volume mounts are defined for each plugin template like so:
```yaml
volumeMounts:
  - mountPath: "/data/inputs"
    name: "data-volume-input"
    readOnly: true
  - mountPath: "/data/outputs/5d08443a8870c7246a98b8fe"
    name: "data-volume-output-5d08443a8870c7246a98b8fe"
    readOnly: false
```
However this is not a viable setup for production deployments, which will often be in a multi-node cluster, potentially hosted on the cloud (first target is AWS), with more sophisticated volumes specifications. 

**Proposal**
Ideally, we want to be volume-type agnostic, ie the the type of volume used for hosting WIPP data does not need to be known by the `WIPP-backend` in order to generate the workflow yaml file.
For that we could use [Kubernetes Persistent Volumes and Persistent Volume Claims (PVC)](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), with the following proposal:
- the `WIPP data` volume is defined as a Persistent Volume, type and specifications of volume are defined here
- a matching `WIPP data PVC` is created, 
- the `WIPP-backend` pod will use this PVC during deployment to access the `WIPP data` volume,
- argo workflows yaml files will reference this PVC as well:
```yaml
volumes:
  - name: "data-volume-input"
    persistentVolumeClaim:
      claimName: "wippdata-pvc"
``` 
- plugin templates:
```yaml
volumeMounts:
      - mountPath: "/data/inputs"
        name: "data-volume-input"
        readOnly: true
      - mountPath: "/data/outputs/5d084e188870c72e14a24499"
        name: "data-volume-input"
        readOnly: false
        subPath: "temp/jobs/5d084e188870c72e14a24499"
```
This also simplifies the yaml generation.

This may not support all volume types, as some types may not supporte [ReadWriteMany access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes), which will then become an issue when the workflow tasks are not being executed on the same node where the volume is.

**Additional context**
cc @ktaletsk please feel free to add any additional information, since you are testing with flexVolumes
